### ISSUE TITLE
GET /publication/user-publications/ details: Cannot resolve keyword 'email' into field. Choices are: content, files, id, id_user, id_user_id, publication_date

### ISSUE THREAD

**Issue by CarlossAyala** [No-Country-simulation/c21-16-m-python-react#13]
![image](https://github.com/user-attachments/assets/d593334a-226f-484e-b6e8-18e5e2e1d0f2)

**Comment by LLFELIPEVV** [comment]
Es el mismo error que me daba con el de perfil, avance con algo mas y en la tarde envio la solucion.
