### ISSUE TITLE
deberíamos agregar el endpoint /users/:id ?

### ISSUE THREAD

**Issue by CarlossAyala** [No-Country-simulation/c21-16-m-python-react#14]
Hay endpoints que devuelven *id_user*, como por ejemplo `GET /publication/publications/`, el `backend` agregará este endpoint o devolveran los usuarios en las respuestas?

**Comment by LLFELIPEVV** [comment]
Esto es lo que devuelve actualmente ese endpoint:
![image](https://github.com/user-attachments/assets/dcb9404a-048c-4ff6-a30e-2c4f65fb2b88)

**Comment by CarlossAyala** [comment]
Puedes agregar una descripción a cada endpoint, cuál es su propósito?
