### ISSUE TITLE
`/api/posts/user-publications/{id}/` debería retornar un json

### ISSUE THREAD

**Issue by CarlossAyala** [No-Country-simulation/c21-16-m-python-react#27]
Si bien el endpoint funciona, debería devolver un json, con cualquier mensaje, pero un json al fin, algo como { message: "ok" }. Ya había explicado porque.

**Comment by LLFELIPEVV** [comment]
Devuelve esto:
![image](https://github.com/user-attachments/assets/c88d1e45-2d37-4605-9bc3-9de7dcb394e9)

**Comment by CarlossAyala** [comment]
Me olvidé el method, es el DELETE xdd, ahí devuelve un "No Content", osea, 204
