### ISSUE TITLE
/auth/register deberia devolver un json

### ISSUE THREAD

**Issue by CarlossAyala** [No-Country-simulation/c21-16-m-python-react#9]
Mientras devuelva un json, el mensaje puede ser cualquiera, pero ahora mismo está devolviendo nada y al hacer `response.json()` se lanza el siguiente error `SyntaxError: Unexpected end of JSON input`. Sugerencia, podrían devolver un { message: "Register successfully"}

**Comment by CarlossAyala** [comment]
Si bien puedo hacer `response.text`, estoy usando la siguiente función:
```js
export const fetcher = async (input, init) => {
  const request = await fetch(input, init);
  const response = await request.json();

  if (!request.ok) {
    throw new Error(response || request.statusText);
  }

  return response;
};
```
Que me ayuda como template para todas las request a los endpoints

**Comment by LLFELIPEVV** [comment]
Pero devuelve 201 y ya no? o no devuelve nada?

**Comment by CarlossAyala** [comment]
Si, devuelve un 201, pero no devuelve nada, y como mencioné en el comentario de arriba, si no hay nada en la respuesta, me lanza un error al intentar hacer response.json()

**Comment by LLFELIPEVV** [comment]
Ah, pero funciona, entonces ahorita subo el cambio.

**Comment by CarlossAyala** [comment]
Si, funciona, debí aclarar eso, pero como también dije, al no devolver nada, al intentar hacer un parse a json me tira un error error, ya que estoy usando la función `fetcher` como template para fetchear los endpoints y lanzar un error cuando el status code de la request sea mayor a 299
